/**
 * Smart Switches
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class LayoutV4 {
    '_1'?: string;
    '_2'?: string;
    '_3'?: string;
    '_4'?: string;
    '_5'?: string;
    '_6'?: string;
    '_7'?: string;
    '_8'?: string;
    'off'?: string;
    'on'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "_1",
            "baseName": "1",
            "type": "string",
            "format": ""
        },
        {
            "name": "_2",
            "baseName": "2",
            "type": "string",
            "format": ""
        },
        {
            "name": "_3",
            "baseName": "3",
            "type": "string",
            "format": ""
        },
        {
            "name": "_4",
            "baseName": "4",
            "type": "string",
            "format": ""
        },
        {
            "name": "_5",
            "baseName": "5",
            "type": "string",
            "format": ""
        },
        {
            "name": "_6",
            "baseName": "6",
            "type": "string",
            "format": ""
        },
        {
            "name": "_7",
            "baseName": "7",
            "type": "string",
            "format": ""
        },
        {
            "name": "_8",
            "baseName": "8",
            "type": "string",
            "format": ""
        },
        {
            "name": "off",
            "baseName": "off",
            "type": "string",
            "format": ""
        },
        {
            "name": "on",
            "baseName": "on",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return LayoutV4.attributeTypeMap;
    }

    public constructor() {
    }
}
