services:
  server:
    container_name: smart-switches-server
    image: ha-smart-switches-server
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "8124:8124"
    volumes:
      - ./data:/data
    environment:
      LOCAL: true
