version: "1.1.8.0"
name: "Smart Switches"
description: "Configure smart switches in your home"
slug: "smart-switches"
url: "https://github.com/lucaspopp0/ha-smart-switches/blob/main/smart-switches"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: application
init: false
panel_icon: 'mdi:light-switch-off'
webui: http://[HOST]:[PORT:8000]
ports:
  8000/tcp: 8000
homeassistant_api: true
