version: "1.1.66.1"
name: "Smart Switches"
description: "Configure smart switches in your home"
slug: "smart-switches"
url: "https://github.com/lucaspopp0/ha-smart-switches/blob/main/smart-switches"
# image: ghcr.io/lucaspopp0/smart-switches
arch:
  - aarch64
  - amd64
  # - armhf
  - armv7
  - i386
startup: application
init: false
panel_icon: 'mdi:puzzle'
panel_admin: false
webui: http://[HOST]:[PORT:8000]
ports:
  8000/tcp: 8000
homeassistant_api: true
