name: "Smart Switches"
description: "My first real add-on!"
version: "1.0.2"
slug: "smart-switches"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
ports:
  8000/tcp: 8000
