name: "Smart Switches"
description: "Configure smart switches in your home"
version: "1.1.2.0"
slug: "smart-switches"
image: "docker.io/lucaspopp0/ha-smart-switches"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: application
webui: http://[HOST]:[PORT:8000]
ports:
  8000/tcp: 8000
homeassistant_api: true
