name: build-site

on:
  workflow_call:
    secrets:
      BOT_APP_ID:
        required: true
      BOT_APP_PRIVATE_KEY:
        required: true

permissions:
  contents: read
  id-token: write

defaults:
  run:
    shell: bash

jobs:

  build-site:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: smart-switches/site
    steps:
      -
        uses: actions/checkout@v4
      -
        uses: actions/setup-node@v4
        with:
          node-version-file: smart-switches/site/.nvmrc
          cache-dependency-path: smart-switches/site/package-lock.json
      -
        name: Install dependencies
        run: |
          npm ci
      -
        name: Build site
        run: |
          rm -rf smart-switches/site/public
          npm run build
      -
        name: Check for generated changes
        id: detect-changes
        run: |
          git status

          if [[ -n "$(git status -s)" ]]; then
            echo "changes=true" | tee -a "$GITHUB_OUTPUT"
          else
            echo "changes=false" | tee -a "$GITHUB_OUTPUT"
          fi
      -
        uses: actions/create-github-app-token@v1
        if: ${{ steps.detect-changes.outputs.changes == 'true' }}
        id: app-token
        with:
          app-id: ${{ secrets.BOT_APP_ID }}
          private-key: ${{ secrets.BOT_APP_PRIVATE_KEY }}
      -
        name: Commit changes
        if: ${{ steps.detect-changes.outputs.changes == 'true' }}
        uses: planetscale/ghcommit-action@v0.2.0
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
        with:
          commit_message: Re-generate site
          repo: ${{ github.repository }}
          branch: ${{ github.head_ref || github.ref_name }}
