name: build-site

on:
  workflow_call:
    secrets:
      BOT_APP_ID:
        required: true
      BOT_APP_PRIVATE_KEY:
        required: true
      DOCKER_USER:
        required: true
      DOCKER_TOKEN:
        required: true

permissions:
  contents: read
  id-token: write

defaults:
  run:
    shell: bash

jobs:

  build-site:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: smart-switches/site
    steps:
      -
        uses: actions/checkout@v4
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}
      -
        uses: actions/setup-go@v5
        with:
          go-version-file: smart-switches/server/go.mod
          cache-dependency-path: smart-switches/server/go.sum
      -
        uses: actions/setup-node@v4
        with:
          node-version-file: smart-switches/site/.nvmrc
          cache-dependency-path: smart-switches/site/package-lock.json
      -
        name: Install dependencies
        working-directory: smart-switches/site
        run: |
          npm ci
      -
        name: Generate OpenAPI types for api
        working-directory: smart-switches
        run: |
          cd server
          go run . get-openapi > ${{ runner.temp }}/openapi.json
          cd ../site
          npx openapi-typescript ${{ runner.temp }}/openapi.json -o ./src/sdk.d.ts
      -
        name: Build site
        working-directory: smart-switches/site
        run: |
          rm -rf public
          npm run build
      -
        name: Check for generated changes
        id: detect-changes
        run: |
          git add .
          git status

          if [[ -n "$(git status -s)" ]]; then
            echo "changes=true" | tee -a "$GITHUB_OUTPUT"
          else
            echo "changes=false" | tee -a "$GITHUB_OUTPUT"
          fi
      -
        uses: actions/create-github-app-token@v1
        if: ${{ steps.detect-changes.outputs.changes == 'true' }}
        id: app-token
        with:
          app-id: ${{ secrets.BOT_APP_ID }}
          private-key: ${{ secrets.BOT_APP_PRIVATE_KEY }}
      -
        name: Commit changes
        if: ${{ steps.detect-changes.outputs.changes == 'true' }}
        uses: planetscale/ghcommit-action@v0.2.0
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
        with:
          commit_message: Re-generate site
          repo: ${{ github.repository }}
          branch: ${{ github.head_ref || github.ref_name }}
      # -
      #   name: Build and publish
      #   uses: home-assistant/builder@master
      #   with:
      #     args: |
      #       --version "pr${{ github.event.number }}-${{ github.sha }}" \
      #       --docker-hub lucaspopp0/ha-smart-switches \
      #       --all
