name: pr

on:
  pull_request:
    types:
      - synchronize
      - opened
      - reopened

permissions:
  contents: write

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  setup:
    runs-on: ubuntu-latest
    outputs:
      changes: ${{ steps.changes.outputs.changes }}
    steps:
      -
        uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            tag-and-release:
              - '.github/workflows/tag-and-release.yaml'

  preview-release:
    needs: setup
    if: ${{ contains(fromJson(needs.setup.outputs.changes), 'tag-and-release') }}
    uses: ./.github/workflows/tag-and-release.yaml
