name: push

on:
  push:
    branches: [main]

permissions:
  contents: write
  pull-requests: read
  id-token: write

defaults:
  run:
    shell: bash

jobs:

  detect-changes:
    uses: ./.github/workflows/detect-changes.yml
    secrets: inherit

  version-update:
    needs: detect-changes
    if: ${{ needs.detect-changes.outputs.smart-switches == 'true' || needs.detect-changes.outputs.workflows == 'true' }}
    uses: ./.github/workflows/version-update.yml
    secrets: inherit

  build-and-push:
    needs: version-update
    uses: ./.github/workflows/docker-build.yml
    with:
      ref: ${{ needs.version-update.outputs.update-sha }}
      push: true
    secrets: inherit
