name: push

on:
  push:
    branches: [main]

permissions:
  contents: write
  pull-requests: read
  id-token: write

defaults:
  run:
    shell: bash

jobs:

  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      changes: ${{ steps.path-filters.outputs.changes }}
      smart-switches: ${{ contains(fromJson(steps.path-filters.outputs.changes), 'smart-switches') }}
      version-update: ${{ contains(fromJson(steps.path-filters.outputs.changes), 'smart-switches') }}
    steps:
      -
        uses: actions/checkout@v4
      -
        name: Detect changes
        uses: dorny/paths-filter@v3
        id: path-filters
        with:
          filters: |
            smart-switches:
              - 'smart-switches/**'
            version-update:
              - './.github/workflows/version-update.yml'

  version-update:
    needs: detect-changes
    if: ${{ needs.detect-changes.outputs.smart-switches == 'true' || needs.detect-changes.outputs.version-update == 'true' }}
    uses: ./.github/workflows/version-update.yml
    secrets: inherit
