name: release-version

run-name: Release ${{ github.ref_name }}

on:
  push:
    tags:
      - 'v*'

permissions:
  id-token: write

defaults:
  run:
    shell: bash

jobs:

  release:
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@v4
      -
        name: Generate release
        run: |
          gh release create \
            --generate-notes \
            -t ${{ github.ref_name }}
  
  build-and-push:
    uses: ./.github/workflows/docker-build.yml
    with:
      push: true
    secrets: inherit
