name: version-update

on:
  workflow_call:

permissions:
  contents: write

jobs:

  version-update:
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      -
        name: Bump version
        id: version
        uses: paulhatch/semantic-version@v5.4.0
        with:
          tag_prefix: ""
          version_format: "${major}.${minor}.${patch}-prerelease${increment}"
          enable_prerelease_mode: true
